### ISSUE TITLE
Incluir contêiner Samba 4 na stack de DEV

### ISSUE THREAD

**Issue by empereira** [ateliedosoftware/atelie-dev-stack#2]
Proporciona a entrega de valor imediata para o campus, que utiliza Samba 4 e ao mesmo tempo facilita a melhoria contínua do backend, tornando a API agnóstica de tecnologia, portanto compatível com  OpenLDAP e Samba4.

Alguns exemplos de containers:

https://github.com/tgiesela/samba4-ad-dc
https://github.com/plaxon/docker-samba4
https://github.com/xnandersson/docker-dc

**Comment by tiagojulianoferreira** [comment]
Vou fazer uma tentativa me baseando no primeiro exemplo. Só fiquei na dúvida como incluo os parâmetros acionais pra rodar a primeira vez a imagem, pra configurar o controlador de domínio.

Esses parâmetros no caso:

`       
         --privileged 
          -h pdc 
        --name dc1 
        --dns-search=test.local 
        --dns=127.0.0.1 
        --net=dvv 
       --ip=<your-fixed-ip-address> 
        -d yourimage
        
  `

**Comment by tiagojulianoferreira** [comment]
Consegui subir o samba4 no Docker e buildei a imagem abaixo, falta incorporar no compose:
https://hub.docker.com/repository/docker/tiagojferreira/samba4
